import { createPublicClient, http } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { join } from 'node:path';
import { arcTestnet, ARC_USDC_ADDRESS, ARC_EXPLORER } from '../worker/src/lib/chains.js';

const USDC_BAL_ABI = [{ type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'a', type: 'address' }], outputs: [{ type: 'uint256' }] }] as const;

const SCENARIOS: { type: string; expect: string }[] = [
  { type: 'good', expect: 'release' },
  { type: 'bad', expect: 'refund' },
  { type: 'abstain', expect: 'abstain' },
  { type: 'schema', expect: 'release' },
];

// Everything below this marker in submission/proof.md is regenerated each seed run.
// Everything ABOVE it (deploy table, EIP-3009 spine, HERO proof) is preserved — the
// seed never destroys the prior on-chain proof. See PLAN Phase 5 Gate 1.
const SEED_MARKER = '<!-- SEED:DEMO-RUNS -->';

function newWorkId(): `0x${string}` {
  return (`0x${randomBytes(32).toString('hex')}`) as `0x${string}`;
}

async function assertFunded() {
  const pub = createPublicClient({ chain: arcTestnet, transport: http(process.env.ARC_RPC_URL) });
  const payer = privateKeyToAccount(process.env.DEMO_PAYER_KEY as `0x${string}`).address;
  const bal = await pub.readContract({ address: ARC_USDC_ADDRESS, abi: USDC_BAL_ABI, functionName: 'balanceOf', args: [payer] });
  const usdc = Number(bal) / 1e6;
  if (usdc < 6) {
    throw new Error(`Payer ${payer} has ${usdc} USDC — fund via faucet.circle.com (20/2h) before seeding (need >=6 for 4x1 USDC escrows + gas).`);
  }
  console.log(`seed: payer ${payer} funded with ${usdc} USDC`);
}

async function runScenario(s: { type: string; expect: string }): Promise<{ type: string; verdict: string; outcome: string; txHash: string | null; error?: string }> {
  const workId = newWorkId();
  // The worker funds the escrow on-chain (real EIP-3009) then runs the verdict + settles.
  // Funding lives in the worker (single funding path) to avoid double-funding the escrow.
  const res = await fetch(`${process.env.WORKER_URL}/api/demo/${s.type}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Demo-Secret': process.env.DEMO_SHARED_SECRET ?? '' },
    body: JSON.stringify({ workId, amountUsdc: 1 }),
  });
  const data = (await res.json()) as { verdict: string; outcome: string; txHash: string | null; error?: string };
  console.log(`seed[${s.type}]: verdict=${data.verdict} outcome=${data.outcome} tx=${data.txHash}${data.error ? ' err=' + data.error : ''}`);
  return { type: s.type, verdict: data.verdict, outcome: data.outcome, txHash: data.txHash, error: data.error };
}

// Build the regenerated seed section (everything below SEED_MARKER).
function seedSection(results: { type: string; verdict: string; outcome: string; txHash: string | null; error?: string }[]): string {
  const escrow = process.env.ESCROW_ADDRESS ?? '';
  const settled = results.filter((r) => r.txHash);
  return [
    SEED_MARKER,
    '',
    '## Seed Demo Runs — real Arc settlements',
    '',
    `Escrow: \`${escrow}\` · Explorer: ${ARC_EXPLORER}/address/${escrow}`,
    `Generated by \`scripts/seed-demo.ts\` (idempotent; fresh workIds each run). Real settlements this run: **${settled.length}**.`,
    '',
    '| Scenario | Verdict | Outcome | Settlement Tx |',
    '|---|---|---|---|',
    ...results.map((r) => `| ${r.type} | ${r.verdict ?? '—'} | ${r.outcome ?? '—'} | ${r.txHash ? `[${r.txHash.slice(0, 14)}…](${ARC_EXPLORER}/tx/${r.txHash})` : (r.error ? `ERROR: ${r.error}` : 'ERROR')} |`),
    '',
    '> `good → abstain/refund-default` is expected while the Anthropic reasoner has no credits (KR-4): the engine abstains conservatively rather than false-certify, so the USDC is refunded to the payer. The release mechanism itself is proven above (DCW-signed `settle()`).',
    '',
  ].join('\n');
}

// Preserve the existing proof.md (deploy + hero tables); replace only the seed section.
async function writeProof(results: { type: string; verdict: string; outcome: string; txHash: string | null; error?: string }[]): Promise<void> {
  await mkdir('submission', { recursive: true });
  const path = join('submission', 'proof.md');
  let existing = '';
  try { existing = await readFile(path, 'utf8'); } catch { /* first run: no file */ }

  const section = seedSection(results);
  let next: string;
  if (existing.includes(SEED_MARKER)) {
    next = existing.slice(0, existing.indexOf(SEED_MARKER)).trimEnd() + '\n\n' + section;
  } else if (existing.trim()) {
    next = existing.trimEnd() + '\n\n' + section;
  } else {
    next = `# On-Chain Proof — Verdikt (Arc edition)\n\n${section}`;
  }
  await writeFile(path, next, 'utf8');
  console.log('seed: wrote submission/proof.md (preserved prior proof above the seed marker)');
}

async function main() {
  await assertFunded();
  const results: Array<{ type: string; verdict: string; outcome: string; txHash: string | null; error?: string }> = [];
  for (const s of SCENARIOS) results.push(await runScenario(s));

  await writeProof(results);

  const settled = results.filter((r) => r.txHash).length;
  console.log(`seed: ${settled}/${results.length} scenarios settled on-chain.`);
  if (settled < 4) {
    console.error(`seed: only ${settled} on-chain settlements (<4) — check worker logs.`);
    process.exit(1);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
